const std = @import("std");
const glfw = @import("glfw");

const root = @import("app.zig");

pub fn keyFromGlfw(key: glfw.Key) root.ZuilCore.input.ZKey {
	return switch (key) {
		.unknown => .unknown,
		.a => .a,
		.b => .b,
		.c => .c,
		.d => .d,
		.e => .e,
		.f => .f,
		.g => .g,
		.h => .h,
		.i => .i,
		.j => .j,
		.k => .k,
		.l => .l,
		.m => .m,
		.n => .n,
		.o => .o,
		.p => .p,
		.q => .q,
		.r => .r,
		.s => .s,
		.t => .t,
		.u => .u,
		.v => .v,
		.w => .w,
		.x => .x,
		.y => .y,
		.z => .z,
		.zero => .num_0,
		.one => .num_1,
		.two => .num_2,
		.three => .num_3,
		.four => .num_4,
		.five => .num_5,
		.six => .num_6,
		.seven => .num_7,
		.eight => .num_8,
		.nine => .num_9,
		.space => .space,
		.kp_0 => .numpad_0,
		.kp_1 => .numpad_1,
		.kp_2 => .numpad_2,
		.kp_3 => .numpad_3,
		.kp_4 => .numpad_4,
		.kp_5 => .numpad_5,
		.kp_6 => .numpad_6,
		.kp_7 => .numpad_7,
		.kp_8 => .numpad_8,
		.kp_9 => .numpad_9,
		.F1 => .fn_1,
		.F2 => .fn_2,
		.F3 => .fn_3,
		.F4 => .fn_4,
		.F5 => .fn_5,
		.F6 => .fn_6,
		.F7 => .fn_7,
		.F8 => .fn_8,
		.F9 => .fn_9,
		.F10 => .fn_10,
		.F11 => .fn_11,
		.F12 => .fn_12,
		.F13 => .fn_13,
		.F14 => .fn_14,
		.F15 => .fn_15,
		.F16 => .fn_16,
		.F17 => .fn_17,
		.F18 => .fn_18,
		.F19 => .fn_19,
		.F20 => .fn_20,
		.F21 => .fn_21,
		.F22 => .fn_22,
		.F23 => .fn_23,
		.F24 => .fn_24,
		.left_shift => .left_shift,
		.right_shift => .right_shift,
		.left_control => .left_control,
		.right_control => .right_control,
		.left_alt => .left_alt,
		.right_alt => .right_alt,
		.left_super => .left_super,
		.right_super => .right_super,
		else => .unknown,
	};
}

pub fn mouseKeyFromGlfw(action: glfw.MouseButton) root.ZuilCore.input.ZMouseKey {
	return switch (action) {
		.right => .right,
		.middle => .middle,
		.left => .left,
		.four => .four,
		.five => .five,
		.six => .six,
		.seven => .seven,
		.eight => .eight,
	};
}

pub fn actionFromGlfw(action: glfw.Action) root.ZuilCore.input.ZAction {
	return switch (action) {
		.press => .press,
		.repeat => .hold,
		.release => .release,
	};
}
