const std = @import("std");
const c = @import("c");

const root = @import("app.zig");

pub fn keyFromSDL(key: u32) root.ZuilCore.input.ZKey {
	return switch (key) {
		c.SDLK_UNKNOWN => .unknown,
		c.SDLK_A => .a,
		c.SDLK_B => .b,
		c.SDLK_C => .c,
		c.SDLK_D => .d,
		c.SDLK_E => .e,
		c.SDLK_F => .f,
		c.SDLK_G => .g,
		c.SDLK_H => .h,
		c.SDLK_I => .i,
		c.SDLK_J => .j,
		c.SDLK_K => .k,
		c.SDLK_L => .l,
		c.SDLK_M => .m,
		c.SDLK_N => .n,
		c.SDLK_O => .o,
		c.SDLK_P => .p,
		c.SDLK_Q => .q,
		c.SDLK_R => .r,
		c.SDLK_S => .s,
		c.SDLK_T => .t,
		c.SDLK_U => .u,
		c.SDLK_V => .v,
		c.SDLK_W => .w,
		c.SDLK_X => .x,
		c.SDLK_Y => .y,
		c.SDLK_Z => .z,
		c.SDLK_0 => .num_0,
		c.SDLK_1 => .num_1,
		c.SDLK_2 => .num_2,
		c.SDLK_3 => .num_3,
		c.SDLK_4 => .num_4,
		c.SDLK_5 => .num_5,
		c.SDLK_6 => .num_6,
		c.SDLK_7 => .num_7,
		c.SDLK_8 => .num_8,
		c.SDLK_9 => .num_9,
		c.SDLK_SPACE => .space,
		c.SDLK_KP_0 => .numpad_0,
		c.SDLK_KP_1 => .numpad_1,
		c.SDLK_KP_2 => .numpad_2,
		c.SDLK_KP_3 => .numpad_3,
		c.SDLK_KP_4 => .numpad_4,
		c.SDLK_KP_5 => .numpad_5,
		c.SDLK_KP_6 => .numpad_6,
		c.SDLK_KP_7 => .numpad_7,
		c.SDLK_KP_8 => .numpad_8,
		c.SDLK_KP_9 => .numpad_9,
		c.SDLK_F1 => .fn_1,
		c.SDLK_F2 => .fn_2,
		c.SDLK_F3 => .fn_3,
		c.SDLK_F4 => .fn_4,
		c.SDLK_F5 => .fn_5,
		c.SDLK_F6 => .fn_6,
		c.SDLK_F7 => .fn_7,
		c.SDLK_F8 => .fn_8,
		c.SDLK_F9 => .fn_9,
		c.SDLK_F10 => .fn_10,
		c.SDLK_F11 => .fn_11,
		c.SDLK_F12 => .fn_12,
		c.SDLK_F13 => .fn_13,
		c.SDLK_F14 => .fn_14,
		c.SDLK_F15 => .fn_15,
		c.SDLK_F16 => .fn_16,
		c.SDLK_F17 => .fn_17,
		c.SDLK_F18 => .fn_18,
		c.SDLK_F19 => .fn_19,
		c.SDLK_F20 => .fn_20,
		c.SDLK_F21 => .fn_21,
		c.SDLK_F22 => .fn_22,
		c.SDLK_F23 => .fn_23,
		c.SDLK_F24 => .fn_24,
		c.SDLK_LSHIFT => .left_shift,
		c.SDLK_RSHIFT => .right_shift,
		c.SDLK_LCTRL => .left_control,
		c.SDLK_RCTRL => .right_control,
		c.SDLK_LALT => .left_alt,
		c.SDLK_RALT => .right_alt,
		c.SDLK_LGUI => .left_super,
		c.SDLK_RGUI => .right_super,
		else => .unknown,
	};
}

pub fn mouseKeyFromSDL(action: u8) root.ZuilCore.input.ZMouseKey {
	return switch (action) {
		c.SDL_BUTTON_RIGHT => .right,
		c.SDL_BUTTON_MIDDLE => .middle,
		c.SDL_BUTTON_LEFT => .left,
		c.SDL_BUTTON_X1 => .four,
		c.SDL_BUTTON_X2 => .five,
		else => .unknown
	};
}

pub fn actionFromSDL(down: bool, repeat: bool) root.ZuilCore.input.ZAction {
	if (repeat) return .hold else if (down) return .press else return .release;
}
